server:
  port: 8080

spring:
  application:
    name: report
  r2dbc:
    url: r2dbc:postgresql://neondb_owner:sxWq28JLvKUX@ep-noisy-queen-a58mwjku.us-east-2.aws.neon.tech/neondb?sslmode=require
    show-sql: true
    pool:
      max-size: 20
      validation-query: SELECT 1
      initial-size: 5
  codec:
    max-in-memory-size: 10MB  # Aumenta el límite de bytes a 10 MB (ajusta según sea necesario)

logging:
  level:
    io.r2dbc: DEBUG